# Generated by Django 4.1.2 on 2022-11-22 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tweet",
            options={"verbose_name_plural": "Tweet"},
        ),
    ]
